{% set name = "geomcompare" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7e88099f531f3d8dfd293eb1ed29121ce70b214d2581ad6b33ce33b75200fdc9
  md5: 99115b09a972b0c53babbe074cdd0747

build:
  number: 0
  skip: True # [py < 39]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - shapely
    - psycopg
    - rtree
    - pyproj
    - gdal

test:
  imports:
    - geomcompare

about:
  home: https://github.com/kartverket/GeomCompare
  summary: "Compare two sets of geometrical features."
  description: |
    GeomCompare provides multiple tools for comparing two independant
    sets of geometrical features. It can be used to identify features
    with similar geometry (based on pre-defined similarity functions)
    found in both sets, as well features with geometry that are found
    in only one of the sets. GeomCompare defines a few similarity
    functions, but it possible for the user to define its own
    customized similarity functions.
  license: GPL-3.0-or-later
  doc_url: https://geomcompare.readthedocs.io/
